--Transact SQL

CREATE DATABASE PV_319_DLL
ON
(
	NAME = PV_319_DLL,
	FILENAME = 'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\PV_319_DLL.mdf',
	SIZE =8 MB,
	MAXSIZE =512 MB,
	FILEGROWTH = 8MB
)
LOG ON
(
NAME				=PV_319_DLL_Log,
FILENAME			='C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\PV_319_DLL_Log.ldf',
SIZE				=8 MB,
MAXSIZE			=512 MB,
FILEGROWTH		=8 MB
);